const products = [
  {id:101,name:'Wireless Mouse',category:'Electronics',price:799,stock:50,description:'2.4 GHz wireless mouse',image:'https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=800&q=82',tag:'A DESK FAVOURITE'},
  {id:102,name:'Mechanical Keyboard',category:'Electronics',price:2499,stock:30,description:'Backlit mechanical keyboard',image:'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=82',tag:'WELL MADE'},
  {id:103,name:'USB-C Hub',category:'Electronics',price:1299,stock:40,description:'6-in-1 USB-C hub',image:'https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=800&q=82',tag:''},
  {id:104,name:'Bluetooth Headphones',category:'Electronics',price:1999,stock:25,description:'Over-ear wireless headphones',image:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=82',tag:'GOOD SOUND'},
  {id:105,name:'Cotton T-Shirt',category:'Clothing',price:499,stock:100,description:'Round neck cotton t-shirt',image:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=82',tag:'EASY EVERYDAY'},
  {id:106,name:'Denim Jeans',category:'Clothing',price:1499,stock:60,description:'Slim fit denim jeans',image:'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=800&q=82',tag:''},
  {id:107,name:'Running Shoes',category:'Clothing',price:2999,stock:35,description:'Lightweight running shoes',image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=82',tag:'ON THE MOVE'},
  {id:108,name:'Steel Water Bottle',category:'Home & Kitchen',price:599,stock:80,description:'1 litre insulated bottle',image:'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=82',tag:'DAILY ESSENTIAL'},
  {id:109,name:'Non-stick Pan',category:'Home & Kitchen',price:899,stock:45,description:'24 cm non-stick frying pan',image:'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=82',tag:''},
  {id:110,name:'Fiction Paperback',category:'Books',price:349,stock:120,description:'A bestselling novel',image:'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=800&q=82',tag:'A GOOD READ'},
  {id:111,name:'Yoga Mat',category:'Sports & Fitness',price:999,stock:0,description:'6 mm anti-slip yoga mat',image:'https://images.unsplash.com/photo-1592432678016-e910b452f9a2?auto=format&fit=crop&w=800&q=82',tag:'OUT OF STOCK'},
  {id:112,name:'The Alchemist',category:'Books',price:399,stock:75,description:'A much-loved paperback novel',image:'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=800&q=82',tag:'READER FAVOURITE'},
  {id:113,name:'Ikigai',category:'Books',price:349,stock:60,description:'A thoughtful guide to finding purpose',image:'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=800&q=82',tag:'GOOD READ'},
  {id:114,name:'The Hobbit',category:'Books',price:499,stock:40,description:'Fantasy adventure paperback',image:'https://images.unsplash.com/photo-1519682337058-a94d519337bc?auto=format&fit=crop&w=800&q=82',tag:'CLASSIC'},
  {id:115,name:'Badminton Racquet',category:'Sports & Fitness',price:899,stock:24,description:'Lightweight racquet for casual play',image:'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=800&q=82',tag:'COURT READY'},
  {id:116,name:'Shuttlecock Set',category:'Sports & Fitness',price:349,stock:55,description:'Pack of six practice shuttlecocks',image:'https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?auto=format&fit=crop&w=800&q=82',tag:'SET OF 6'},
  {id:117,name:'Cricket Tennis Balls',category:'Sports & Fitness',price:299,stock:70,description:'Pack of three practice cricket balls',image:'https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=800&q=82',tag:'PRACTICE SET'},
  {id:118,name:'Cricket Bat',category:'Sports & Fitness',price:1499,stock:18,description:'Willow practice bat for weekend games',image:'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=800&q=82',tag:'GAME ON'},
  {id:119,name:'Training Football',category:'Sports & Fitness',price:799,stock:28,description:'Durable ball for training and play',image:'https://images.unsplash.com/photo-1614632537423-1e6c2e7e0d7a?auto=format&fit=crop&w=800&q=82',tag:'GET MOVING'},
  {id:120,name:'Kids Floral Dress',category:'Kids Fashion',price:899,stock:22,description:'Soft cotton floral dress for children',image:'https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?auto=format&fit=crop&w=800&q=82',tag:'KIDS FAVOURITE'},
  {id:121,name:'Kids Kurta Set',category:'Kids Fashion',price:799,stock:16,description:'Comfortable cotton kurta and pajama set',image:'https://images.unsplash.com/photo-1519457431-44ccd64a579b?auto=format&fit=crop&w=800&q=82',tag:'FESTIVE PICK'},
  {id:122,name:'Kids T-Shirt Set',category:'Kids Fashion',price:599,stock:30,description:'Two-piece everyday cotton outfit',image:'https://images.unsplash.com/photo-1503919005314-30d93d07d823?auto=format&fit=crop&w=800&q=82',tag:'EASY EVERYDAY'},
  {id:123,name:'Wooden Building Blocks',category:'Toys',price:699,stock:32,description:'Colourful wooden blocks for creative play',image:'https://images.unsplash.com/photo-1599623560574-39d485900c95?auto=format&fit=crop&w=800&q=82',tag:'PLAY & LEARN'},
  {id:124,name:'Plush Teddy Bear',category:'Toys',price:499,stock:26,description:'Soft cuddly teddy bear',image:'https://images.unsplash.com/photo-1559454403-b8fb88521f11?auto=format&fit=crop&w=800&q=82',tag:'SOFT & CUDDLY'},
  {id:125,name:'Remote Control Car',category:'Toys',price:1299,stock:15,description:'Rechargeable remote control toy car',image:'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=800&q=82',tag:'READY TO RACE'},
  {id:126,name:'Jigsaw Puzzle Set',category:'Toys',price:399,stock:35,description:'A colourful 100-piece family puzzle',image:'https://images.unsplash.com/photo-1606503153255-59d8b8b82155?auto=format&fit=crop&w=800&q=82',tag:'FAMILY FUN'},
  {id:127,name:'Electric Kettle',category:'Home & Kitchen',price:1299,stock:20,description:'1.5 litre stainless steel kettle',image:'https://images.unsplash.com/photo-1594213114663-d94db9b171e5?auto=format&fit=crop&w=800&q=82',tag:'KITCHEN ESSENTIAL'},
  {id:128,name:'Glass Storage Set',category:'Home & Kitchen',price:699,stock:34,description:'Set of three glass food containers',image:'https://images.unsplash.com/photo-1603199506016-b9a594b593c0?auto=format&fit=crop&w=800&q=82',tag:'SET OF 3'},
  {id:129,name:'Cookware Set',category:'Home & Kitchen',price:1899,stock:12,description:'Three-piece everyday cookware set',image:'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&w=800&q=82',tag:'COOK EVERYDAY'},
  {id:130,name:'Kitchen Knife Set',category:'Home & Kitchen',price:599,stock:27,description:'Three-piece stainless steel knife set',image:'https://images.unsplash.com/photo-1593618998160-e34014e67546?auto=format&fit=crop&w=800&q=82',tag:'KITCHEN TOOL'}
];
const categories=['Everything','Electronics','Clothing','Home & Kitchen','Books','Sports & Fitness','Kids Fashion','Toys'];
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
const state={openTracking:new Set(),category:'Everything',query:'',sort:'featured',favorites:new Set(read('nuvora-favorites',[])),cart:read('nuvora-cart',read('goodday-cart',{})),user:read('nuvora-user',null),orders:read('nuvora-orders',[]),favoritesOnly:false};
const $=s=>document.querySelector(s);
const categoryEl=$('#categories'),productsEl=$('#products'),cartEl=$('#cartDrawer'),overlay=$('#overlay');
const moneyLong=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',minimumFractionDigits:2}).format(n);
const API_ENABLED=location.protocol==='https:'||(location.protocol==='http:'&&['localhost','127.0.0.1'].includes(location.hostname));
let authMode='login';
async function apiRequest(url,options={}){const config={method:options.method||'GET',credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})}};if(options.body!==undefined)config.body=JSON.stringify(options.body);const response=await fetch(url,config);let data={};try{data=await response.json()}catch{}if(!response.ok)throw new Error(data.error||'Request failed.');return data}
function saveFavorites(){persist('nuvora-favorites',[...state.favorites]);if(API_ENABLED&&state.user)apiRequest('/api/favorites',{method:'PUT',body:{ids:[...state.favorites]}}).catch(error=>toast(error.message))}
async function refreshRemoteProducts(){if(!API_ENABLED)return;const stock=await apiRequest('/api/products');for(const item of stock){const product=products.find(p=>p.id===item.id);if(product){product.stock=item.stock;product.price=item.price}}renderProducts();renderCart()}
async function loadSharedAccount(){if(!API_ENABLED)return;try{const result=await apiRequest('/api/auth/me');state.user=result.user;persist('nuvora-user',state.user);state.cart=await apiRequest('/api/cart');state.favorites=new Set(await apiRequest('/api/favorites'));state.orders=await apiRequest('/api/orders');persist('nuvora-cart',state.cart);persist('nuvora-favorites',[...state.favorites]);persist('nuvora-orders',state.orders)}catch(error){state.user=null;localStorage.removeItem('nuvora-user');if(error.message!=='Please sign in.')toast(error.message)}try{await refreshRemoteProducts()}catch(error){toast('Shared catalog could not be refreshed: '+error.message)}renderAccountPane();renderProducts();renderCart()}

function persist(key,value){localStorage.setItem(key,JSON.stringify(value))}
function renderCategories(){categoryEl.innerHTML=categories.map(c=>`<button class="category-chip ${state.category===c?'selected':''}" data-category="${c}">${c}</button>`).join('')}
function renderProducts(){let list=products.filter(p=>(state.category==='Everything'||p.category===state.category)&&(`${p.name} ${p.description} ${p.category}`).toLowerCase().includes(state.query.toLowerCase())&&(!state.favoritesOnly||state.favorites.has(p.id)));if(state.sort==='low')list.sort((a,b)=>a.price-b.price);if(state.sort==='high')list.sort((a,b)=>b.price-a.price);if(state.sort==='name')list.sort((a,b)=>a.name.localeCompare(b.name));$('#resultCount').textContent=`${list.length} ${state.favoritesOnly?'saved':'good'} ${list.length===1?'find':'finds'}`;$('#emptyState').hidden=!!list.length;productsEl.hidden=!list.length;productsEl.innerHTML=list.map(p=>`<article class="product-card"><div class="product-visual"><img src="${p.image}" alt="${p.name}" loading="lazy" tabindex="0" role="button" data-open-product="${p.id}" aria-label="View ${p.name} details"><span class="product-tag">${p.stock===0?'OUT OF STOCK':p.tag||p.category.toUpperCase()}</span><button class="heart-btn ${state.favorites.has(p.id)?'liked':''}" data-favorite="${p.id}" aria-label="${state.favorites.has(p.id)?'Remove':'Add'} ${p.name} ${state.favorites.has(p.id)?'from':'to'} saved items">${state.favorites.has(p.id)?'♥':'♡'}</button><button class="add-btn" data-add="${p.id}" ${p.stock===0?'disabled':''}>${p.stock===0?'Out of stock':'+ Add to cart'}</button></div><div class="product-info"><div><div class="product-name" data-open-product="${p.id}" tabindex="0" role="button">${p.name}</div><div class="product-category">${p.category} · ${p.stock} in stock</div></div><div class="product-price">${money(p.price)}</div></div></article>`).join('')}
function qtyTotal(){return Object.values(state.cart).reduce((a,b)=>a+b,0)}
function saveCart(){persist('nuvora-cart',state.cart);renderCart();if(API_ENABLED&&state.user)apiRequest('/api/cart',{method:'PUT',body:state.cart}).catch(error=>toast(error.message))}
function renderCart(){const entries=products.filter(p=>state.cart[p.id]);const count=qtyTotal();$('#bagCount').textContent=count;$('#drawerCount').textContent=`(${count})`;$('#cartEmpty').classList.toggle('visible',!count);$('#cartFooter').classList.toggle('hidden',!count);$('#cartItems').classList.toggle('hidden',!count);$('#cartItems').innerHTML=entries.map(p=>`<div class="cart-row"><img src="${p.image}" alt=""><div class="cart-row-info"><div class="cart-row-name">${p.name}</div><div class="cart-row-category">${p.category}</div><div class="quantity-control"><button data-qty="${p.id}" data-delta="-1" aria-label="Remove one ${p.name}">−</button><span>${state.cart[p.id]}</span><button data-qty="${p.id}" data-delta="1" aria-label="Add one ${p.name}" ${state.cart[p.id]>=p.stock?'disabled':''}>+</button><button class="remove-item" data-remove="${p.id}">Remove</button></div></div><div class="cart-row-price">${money(p.price*state.cart[p.id])}</div></div>`).join('');const subtotal=entries.reduce((s,p)=>s+p.price*state.cart[p.id],0);$('#subtotal').textContent=money(subtotal);$('#shippingProgress').style.width=`${Math.min(100,subtotal/1499*100)}%`;$('#shippingMessage').textContent=subtotal>=1499?'Free delivery unlocked':`Add ${money(1499-subtotal)} for free delivery`}
function addToCart(id){const p=products.find(x=>x.id===id);if(!p||p.stock===0)return;if((state.cart[id]||0)>=p.stock){toast('That is all the stock currently available');return}state.cart[id]=(state.cart[id]||0)+1;saveCart();toast(`${p.name} added to your cart`)}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2400)}
function openProduct(id){const p=products.find(item=>item.id===id);if(!p)return;state.currentProduct=id;$('#detailImage').src=p.image;$('#detailImage').alt=p.name;$('#detailCategory').textContent=p.category;$('#detailName').textContent=p.name;$('#detailPrice').textContent=money(p.price);$('#detailDescription').textContent=p.description;$('#detailStock').textContent=p.stock?`${p.stock} in stock`:'Currently out of stock';$('#detailAdd').disabled=p.stock===0;$('#detailAdd').textContent=p.stock===0?'Out of stock':'Add to cart';$('#detailSave').textContent=state.favorites.has(p.id)?'♥ Saved to wishlist':'♡ Save to wishlist';openModal('detailPane')}
function openCart(){cartEl.classList.add('open');overlay.classList.add('open');cartEl.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeCart(){cartEl.classList.remove('open');overlay.classList.remove('open');cartEl.setAttribute('aria-hidden','true');document.body.style.overflow=''}
function openModal(pane){$('#modalBackdrop').classList.add('open');document.body.style.overflow='hidden';['accountPane','detailPane','checkoutPane','ordersPane','successPane'].forEach(id=>$('#'+id).hidden=id!==pane);if(pane==='accountPane')renderAccountPane();if(pane==='ordersPane')renderOrders();if(pane==='checkoutPane')renderCheckoutSummary()}
function closeModal(){$('#modalBackdrop').classList.remove('open');document.body.style.overflow=''}
function renderAccountPane(){const signed=!!state.user;$('#accountTitle').textContent=signed?'Your account':'Welcome to Nuvora';$('#authForm').hidden=signed;$('#accountDetails').hidden=!signed;$('#accountButton').textContent=signed?'Hi, '+state.user.name.split(' ')[0]:'Login';$('#authNameLabel').hidden=authMode!=='register';$('#authName').required=authMode==='register';$('#authSubmit').innerHTML=(authMode==='register'?'Create account':'Sign in')+' <span>→</span>';$('#authModeToggle').textContent=authMode==='register'?'I already have an account':'Create account';if(signed){$('#accountName').textContent=state.user.name;$('#accountEmail').textContent=state.user.email;$('#orderCount').textContent=state.orders.length;}}
function renderOrders(){
 const box=$('#ordersList');
 if(!state.orders.length){box.innerHTML='<div class="empty-orders"><span>▤</span><h3>No orders yet</h3><p>Your placed orders will show up here.</p></div>';return}
 const stages=['Placed','Processing','Shipped','Delivered'];
 box.innerHTML=state.orders.map(o=>{
  const open=state.openTracking.has(o.id),stage=stages.indexOf(o.status),canCancel=['Placed','Processing'].includes(o.status),next=stages[stage+1];
  const timeline=o.status==='Cancelled'?'<div class="tracking-cancelled">This order was cancelled.</div>':'<div class="tracking-track"><span style="width:'+Math.max(0,stage)*33.33+'%"></span></div><ol class="tracking-steps">'+stages.map((name,index)=>'<li class="'+(index<=stage?'complete':'')+'"><span class="step-dot"></span><b>'+name+'</b><small>'+(index<stage?'Complete':index===stage?'Current status':'Pending')+'</small></li>').join('')+'</ol><div class="tracking-demo-note">Shipment updates are simulated in this website.</div>'+(next?'<button class="advance-tracking" data-advance="'+o.id+'">Simulate next update: '+next+' →</button>':'<div class="delivered-note">Your order has been delivered.</div>');
  const cancel=canCancel?'<button class="cancel-order-btn" data-cancel="'+o.id+'">Cancel order</button>':'';
  return '<article class="order-card"><div class="order-card-head"><strong>Order '+o.id+'</strong><span class="order-status '+(o.status==='Cancelled'?'cancelled':'')+'">'+o.status+'</span></div><div class="order-meta">'+new Date(o.date).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'})+' · '+o.items.length+' item'+(o.items.length===1?'':'s')+'</div><div class="order-lines">'+o.items.map(i=>'<div>'+i.name+' × '+i.quantity+'<span>'+money(i.price*i.quantity)+'</span></div>').join('')+'</div><div class="order-card-total"><span>Total · '+o.paymentMethod+'</span><strong>'+money(o.total)+'</strong></div><div class="order-address">Delivering to '+o.address+'</div><div class="order-actions"><button class="track-order-btn" data-track="'+o.id+'">'+(open?'Hide tracking':'Track order')+'</button>'+cancel+'</div>'+(open?'<div class="tracking-panel">'+timeline+'</div>':'')+'</article>';
 }).join('');
}
function renderCheckoutSummary(){const rows=products.filter(p=>state.cart[p.id]);$('#checkoutSummary').innerHTML=rows.map(p=>`<div class="checkout-line"><span>${p.name} × ${state.cart[p.id]}</span><strong>${moneyLong(p.price*state.cart[p.id])}</strong></div>`).join('');$('#checkoutTotal').textContent=moneyLong(rows.reduce((n,p)=>n+p.price*state.cart[p.id],0))}
function goCheckout(){if(!qtyTotal())return;if(!state.user){closeCart();openModal('accountPane');toast('Sign in or create an account before checkout');return}closeCart();openModal('checkoutPane');$('#shipName').value=state.user.name||''}
categoryEl.addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(b){state.category=b.dataset.category;state.favoritesOnly=false;renderCategories();renderProducts()}});
productsEl.addEventListener('click',e=>{const a=e.target.closest('[data-add]'),f=e.target.closest('[data-favorite]'),d=e.target.closest('[data-open-product]');if(a)addToCart(Number(a.dataset.add));if(d)openProduct(Number(d.dataset.openProduct));if(f){const id=Number(f.dataset.favorite);state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);persist('nuvora-favorites',[...state.favorites]);renderProducts()}});
$('#cartItems').addEventListener('click',e=>{const q=e.target.closest('[data-qty]'),r=e.target.closest('[data-remove]');if(q){const id=q.dataset.qty,next=(state.cart[id]||0)+Number(q.dataset.delta),p=products.find(x=>x.id===Number(id));if(next>p.stock){toast('That is all the stock currently available');return}if(next<=0)delete state.cart[id];else state.cart[id]=next;saveCart()}if(r){delete state.cart[r.dataset.remove];saveCart()}});
$('#searchInput').addEventListener('input',e=>{state.query=e.target.value;renderProducts()});$('#sortSelect').addEventListener('change',e=>{state.sort=e.target.value;renderProducts()});
$('#clearFilters').addEventListener('click',()=>{state.category='Everything';state.query='';state.favoritesOnly=false;$('#searchInput').value='';renderCategories();renderProducts()});
document.querySelectorAll('[data-category-link]').forEach(a=>a.addEventListener('click',()=>{state.category=a.dataset.categoryLink;state.favoritesOnly=false;renderCategories();renderProducts();$('.main-nav').classList.remove('open')}));
document.querySelectorAll('[data-view="favorites"]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();state.favoritesOnly=true;state.category='Everything';renderCategories();renderProducts();$('#shop').scrollIntoView({behavior:'smooth'});$('.main-nav').classList.remove('open')}));
$('#openCart').addEventListener('click',openCart);$('#closeCart').addEventListener('click',closeCart);overlay.addEventListener('click',closeCart);$('#continueShopping').addEventListener('click',closeCart);document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeCart();closeModal()}});$('#menuToggle').addEventListener('click',()=>$('.main-nav').classList.toggle('open'));$('.search-toggle').addEventListener('click',()=>{$('#searchInput').focus();$('#shop').scrollIntoView({behavior:'smooth'})});
productsEl.addEventListener('keydown',e=>{const d=e.target.closest('[data-open-product]');if(d&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openProduct(Number(d.dataset.openProduct))}});$('#detailAdd').addEventListener('click',()=>{if(state.currentProduct){addToCart(state.currentProduct);closeModal()}});$('#detailSave').addEventListener('click',()=>{if(!state.currentProduct)return;state.favorites.has(state.currentProduct)?state.favorites.delete(state.currentProduct):state.favorites.add(state.currentProduct);persist('nuvora-favorites',[...state.favorites]);$('#detailSave').textContent=state.favorites.has(state.currentProduct)?'♥ Saved to wishlist':'♡ Save to wishlist';renderProducts()});$('#checkoutButton').addEventListener('click',goCheckout);document.querySelectorAll('[data-open-account]').forEach(b=>b.addEventListener('click',()=>openModal('accountPane')));document.querySelectorAll('[data-open-orders]').forEach(b=>b.addEventListener('click',()=>openModal('ordersPane')));document.querySelectorAll('[data-close-modal]').forEach(b=>b.addEventListener('click',closeModal));$('#modalBackdrop').addEventListener('click',e=>{if(e.target===$('#modalBackdrop'))closeModal()});
$('#authModeToggle').addEventListener('click',()=>{authMode=authMode==='login'?'register':'login';renderAccountPane()});$('#authForm').addEventListener('submit',async e=>{e.preventDefault();const name=$('#authName').value.trim(),email=$('#authEmail').value.trim().toLowerCase(),password=$('#authPassword').value;try{if(API_ENABLED){const result=await apiRequest(authMode==='register'?'/api/auth/register':'/api/auth/login',{method:'POST',body:{name,email,password}});state.user=result.user;persist('nuvora-user',state.user);if(authMode==='register'){await apiRequest('/api/cart',{method:'PUT',body:state.cart});await apiRequest('/api/favorites',{method:'PUT',body:{ids:[...state.favorites]}})}else{state.cart=await apiRequest('/api/cart');state.favorites=new Set(await apiRequest('/api/favorites'))}state.orders=await apiRequest('/api/orders');persist('nuvora-cart',state.cart);persist('nuvora-orders',state.orders);persist('nuvora-favorites',[...state.favorites]);await refreshRemoteProducts()}else{state.user={name:name||email.split('@')[0],email};persist('nuvora-user',state.user)}renderAccountPane();renderProducts();renderCart();toast('Welcome, '+state.user.name.split(' ')[0]+'!')}catch(error){toast(error.message)}});
$('#logoutButton').addEventListener('click',async()=>{if(API_ENABLED&&state.user){try{await apiRequest('/api/auth/logout',{method:'POST'})}catch(error){toast(error.message)}}state.user=null;localStorage.removeItem('nuvora-user');renderAccountPane();toast('You have signed out')});$('#ordersButton').addEventListener('click',()=>openModal('ordersPane'));$('#ordersList').addEventListener('click',async e=>{const track=e.target.closest('[data-track]'),cancel=e.target.closest('[data-cancel]'),advance=e.target.closest('[data-advance]');if(track){state.openTracking.has(track.dataset.track)?state.openTracking.delete(track.dataset.track):state.openTracking.add(track.dataset.track);renderOrders()}if(cancel){const order=state.orders.find(o=>o.id===cancel.dataset.cancel);if(!order||!['Placed','Processing'].includes(order.status))return;if(!window.confirm('Cancel order '+order.id+'?'))return;try{if(API_ENABLED){await apiRequest('/api/orders/'+encodeURIComponent(order.id)+'/actions',{method:'POST',body:{action:'cancel'}});state.orders=await apiRequest('/api/orders');await refreshRemoteProducts()}else{order.status='Cancelled';order.paymentStatus=order.paymentMethod==='Cash on Delivery'?'Not charged':'Refund initiated (demo)';persist('nuvora-orders',state.orders)}renderOrders();toast('Order cancelled')}catch(error){toast(error.message)}}if(advance){const order=state.orders.find(o=>o.id===advance.dataset.advance);if(!order)return;try{if(API_ENABLED){await apiRequest('/api/orders/'+encodeURIComponent(order.id)+'/actions',{method:'POST',body:{action:'advance'}});state.orders=await apiRequest('/api/orders')}else{const steps=['Placed','Processing','Shipped','Delivered'],index=steps.indexOf(order.status);if(index>=0&&index<steps.length-1)order.status=steps[index+1];persist('nuvora-orders',state.orders)}renderOrders();toast('Tracking updated: '+state.orders.find(o=>o.id===order.id).status)}catch(error){toast(error.message)}}});
$('#checkoutForm').addEventListener('submit',async e=>{e.preventDefault();if(!state.user||!qtyTotal())return;const lines=products.filter(p=>state.cart[p.id]).map(p=>({id:p.id,name:p.name,price:p.price,quantity:state.cart[p.id]}));for(const item of lines){const product=products.find(p=>p.id===item.id);if(item.quantity>product.stock){toast(product.name+' is no longer available in that quantity');return}}const method=document.querySelector('input[name="paymentMethod"]:checked').value,address=$('#shipAddress').value.trim()+', '+$('#shipCity').value.trim()+' '+$('#shipPin').value.trim();let order;try{if(API_ENABLED){const result=await apiRequest('/api/orders',{method:'POST',body:{items:lines.map(item=>({id:item.id,quantity:item.quantity})),paymentMethod:method,address,phone:$('#shipPhone').value.trim()}});order=result.order;state.orders=await apiRequest('/api/orders');await refreshRemoteProducts()}else{const total=lines.reduce((sum,item)=>sum+item.price*item.quantity,0);order={id:'NV'+Date.now().toString().slice(-8),date:new Date().toISOString(),items:lines,total,paymentMethod:method,paymentStatus:method==='Cash on Delivery'?'Pending':'Demo success',status:'Placed',address,email:state.user.email};state.orders.unshift(order);persist('nuvora-orders',state.orders)}state.cart={};persist('nuvora-cart',state.cart);renderCart();if(API_ENABLED)await apiRequest('/api/cart',{method:'PUT',body:{}});state.lastOrderId=order.id;$('#cancelNewOrder').hidden=false;$('#successOrderId').textContent=order.id;$('#successPayment').textContent=method+' · '+order.paymentStatus;openModal('successPane')}catch(error){toast(error.message)}});
$('#viewOrdersAfterCheckout').addEventListener('click',()=>openModal('ordersPane'));$('#cancelNewOrder').addEventListener('click',async()=>{const order=state.orders.find(o=>o.id===state.lastOrderId);if(!order||!['Placed','Processing'].includes(order.status))return;if(!window.confirm('Cancel order '+order.id+'?'))return;try{if(API_ENABLED){await apiRequest('/api/orders/'+encodeURIComponent(order.id)+'/actions',{method:'POST',body:{action:'cancel'}});state.orders=await apiRequest('/api/orders');await refreshRemoteProducts()}else{order.status='Cancelled';order.paymentStatus=order.paymentMethod==='Cash on Delivery'?'Not charged':'Refund initiated (demo)';persist('nuvora-orders',state.orders)}const updated=state.orders.find(o=>o.id===state.lastOrderId);$('#successPayment').textContent=updated.paymentMethod+' · '+updated.paymentStatus;$('#cancelNewOrder').hidden=true;toast('Order cancelled')}catch(error){toast(error.message)}});$('#newsletterForm').addEventListener('submit',e=>{e.preventDefault();const email=$('#emailInput').value;$('#newsletterNote').textContent=`Thanks! Offers will go to ${email}.`;e.target.reset()});
renderCategories();renderProducts();renderCart();renderAccountPane();loadSharedAccount();


